//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by conversion-gen. DO NOT EDIT.

package v2

import (
	unsafe "unsafe"

	v1 "github.com/kyverno/kyverno/api/kyverno/v1"
	admissionregistrationv1 "k8s.io/api/admissionregistration/v1"
	apiextensionsv1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*AnyAllConditions)(nil), (*v1.AnyAllConditions)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v2_AnyAllConditions_To_v1_AnyAllConditions(a.(*AnyAllConditions), b.(*v1.AnyAllConditions), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1.AnyAllConditions)(nil), (*AnyAllConditions)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_AnyAllConditions_To_v2_AnyAllConditions(a.(*v1.AnyAllConditions), b.(*AnyAllConditions), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Attestation)(nil), (*v1.Attestation)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v2_Attestation_To_v1_Attestation(a.(*Attestation), b.(*v1.Attestation), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ClusterPolicy)(nil), (*v1.ClusterPolicy)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v2_ClusterPolicy_To_v1_ClusterPolicy(a.(*ClusterPolicy), b.(*v1.ClusterPolicy), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1.ClusterPolicy)(nil), (*ClusterPolicy)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_ClusterPolicy_To_v2_ClusterPolicy(a.(*v1.ClusterPolicy), b.(*ClusterPolicy), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ClusterPolicyList)(nil), (*v1.ClusterPolicyList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v2_ClusterPolicyList_To_v1_ClusterPolicyList(a.(*ClusterPolicyList), b.(*v1.ClusterPolicyList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1.ClusterPolicyList)(nil), (*ClusterPolicyList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_ClusterPolicyList_To_v2_ClusterPolicyList(a.(*v1.ClusterPolicyList), b.(*ClusterPolicyList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Condition)(nil), (*v1.Condition)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v2_Condition_To_v1_Condition(a.(*Condition), b.(*v1.Condition), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1.Condition)(nil), (*Condition)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_Condition_To_v2_Condition(a.(*v1.Condition), b.(*Condition), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1.Generation)(nil), (*Generation)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_Generation_To_v2_Generation(a.(*v1.Generation), b.(*Generation), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ImageVerification)(nil), (*v1.ImageVerification)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v2_ImageVerification_To_v1_ImageVerification(a.(*ImageVerification), b.(*v1.ImageVerification), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*MatchResources)(nil), (*v1.MatchResources)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v2_MatchResources_To_v1_MatchResources(a.(*MatchResources), b.(*v1.MatchResources), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1.Mutation)(nil), (*Mutation)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_Mutation_To_v2_Mutation(a.(*v1.Mutation), b.(*Mutation), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Policy)(nil), (*v1.Policy)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v2_Policy_To_v1_Policy(a.(*Policy), b.(*v1.Policy), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1.Policy)(nil), (*Policy)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_Policy_To_v2_Policy(a.(*v1.Policy), b.(*Policy), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PolicyList)(nil), (*v1.PolicyList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v2_PolicyList_To_v1_PolicyList(a.(*PolicyList), b.(*v1.PolicyList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1.PolicyList)(nil), (*PolicyList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_PolicyList_To_v2_PolicyList(a.(*v1.PolicyList), b.(*PolicyList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ResourceDescription)(nil), (*v1.ResourceDescription)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v2_ResourceDescription_To_v1_ResourceDescription(a.(*ResourceDescription), b.(*v1.ResourceDescription), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ResourceFilter)(nil), (*v1.ResourceFilter)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v2_ResourceFilter_To_v1_ResourceFilter(a.(*ResourceFilter), b.(*v1.ResourceFilter), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1.ResourceFilter)(nil), (*ResourceFilter)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_ResourceFilter_To_v2_ResourceFilter(a.(*v1.ResourceFilter), b.(*ResourceFilter), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1.Validation)(nil), (*Validation)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_Validation_To_v2_Validation(a.(*v1.Validation), b.(*Validation), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*WebhookConfiguration)(nil), (*v1.WebhookConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v2_WebhookConfiguration_To_v1_WebhookConfiguration(a.(*WebhookConfiguration), b.(*v1.WebhookConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1.WebhookConfiguration)(nil), (*WebhookConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_WebhookConfiguration_To_v2_WebhookConfiguration(a.(*v1.WebhookConfiguration), b.(*WebhookConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1.Attestation)(nil), (*Attestation)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_Attestation_To_v2_Attestation(a.(*v1.Attestation), b.(*Attestation), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1.Deny)(nil), (*Deny)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_Deny_To_v2_Deny(a.(*v1.Deny), b.(*Deny), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1.ImageVerification)(nil), (*ImageVerification)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_ImageVerification_To_v2_ImageVerification(a.(*v1.ImageVerification), b.(*ImageVerification), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1.MatchResources)(nil), (*MatchResources)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_MatchResources_To_v2_MatchResources(a.(*v1.MatchResources), b.(*MatchResources), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1.ResourceDescription)(nil), (*ResourceDescription)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_ResourceDescription_To_v2_ResourceDescription(a.(*v1.ResourceDescription), b.(*ResourceDescription), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1.Rule)(nil), (*Rule)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_Rule_To_v2_Rule(a.(*v1.Rule), b.(*Rule), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1.Spec)(nil), (*Spec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_Spec_To_v2_Spec(a.(*v1.Spec), b.(*Spec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1.TargetResourceSpec)(nil), (*TargetResourceSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_TargetResourceSpec_To_v2_TargetResourceSpec(a.(*v1.TargetResourceSpec), b.(*TargetResourceSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*Deny)(nil), (*v1.Deny)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v2_Deny_To_v1_Deny(a.(*Deny), b.(*v1.Deny), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*Generation)(nil), (*v1.Generation)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v2_Generation_To_v1_Generation(a.(*Generation), b.(*v1.Generation), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*Mutation)(nil), (*v1.Mutation)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v2_Mutation_To_v1_Mutation(a.(*Mutation), b.(*v1.Mutation), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*Rule)(nil), (*v1.Rule)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v2_Rule_To_v1_Rule(a.(*Rule), b.(*v1.Rule), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*Spec)(nil), (*v1.Spec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v2_Spec_To_v1_Spec(a.(*Spec), b.(*v1.Spec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*TargetResourceSpec)(nil), (*v1.TargetResourceSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v2_TargetResourceSpec_To_v1_TargetResourceSpec(a.(*TargetResourceSpec), b.(*v1.TargetResourceSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*Validation)(nil), (*v1.Validation)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v2_Validation_To_v1_Validation(a.(*Validation), b.(*v1.Validation), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v2_AnyAllConditions_To_v1_AnyAllConditions(in *AnyAllConditions, out *v1.AnyAllConditions, s conversion.Scope) error {
	out.AnyConditions = *(*[]v1.Condition)(unsafe.Pointer(&in.AnyConditions))
	out.AllConditions = *(*[]v1.Condition)(unsafe.Pointer(&in.AllConditions))
	return nil
}

// Convert_v2_AnyAllConditions_To_v1_AnyAllConditions is an autogenerated conversion function.
func Convert_v2_AnyAllConditions_To_v1_AnyAllConditions(in *AnyAllConditions, out *v1.AnyAllConditions, s conversion.Scope) error {
	return autoConvert_v2_AnyAllConditions_To_v1_AnyAllConditions(in, out, s)
}

func autoConvert_v1_AnyAllConditions_To_v2_AnyAllConditions(in *v1.AnyAllConditions, out *AnyAllConditions, s conversion.Scope) error {
	out.AnyConditions = *(*[]Condition)(unsafe.Pointer(&in.AnyConditions))
	out.AllConditions = *(*[]Condition)(unsafe.Pointer(&in.AllConditions))
	return nil
}

// Convert_v1_AnyAllConditions_To_v2_AnyAllConditions is an autogenerated conversion function.
func Convert_v1_AnyAllConditions_To_v2_AnyAllConditions(in *v1.AnyAllConditions, out *AnyAllConditions, s conversion.Scope) error {
	return autoConvert_v1_AnyAllConditions_To_v2_AnyAllConditions(in, out, s)
}

func autoConvert_v2_Attestation_To_v1_Attestation(in *Attestation, out *v1.Attestation, s conversion.Scope) error {
	out.Type = in.Type
	out.Attestors = *(*[]v1.AttestorSet)(unsafe.Pointer(&in.Attestors))
	out.Conditions = *(*[]v1.AnyAllConditions)(unsafe.Pointer(&in.Conditions))
	return nil
}

// Convert_v2_Attestation_To_v1_Attestation is an autogenerated conversion function.
func Convert_v2_Attestation_To_v1_Attestation(in *Attestation, out *v1.Attestation, s conversion.Scope) error {
	return autoConvert_v2_Attestation_To_v1_Attestation(in, out, s)
}

func autoConvert_v1_Attestation_To_v2_Attestation(in *v1.Attestation, out *Attestation, s conversion.Scope) error {
	// WARNING: in.PredicateType requires manual conversion: does not exist in peer-type
	out.Type = in.Type
	out.Attestors = *(*[]v1.AttestorSet)(unsafe.Pointer(&in.Attestors))
	out.Conditions = *(*[]AnyAllConditions)(unsafe.Pointer(&in.Conditions))
	return nil
}

func autoConvert_v2_ClusterPolicy_To_v1_ClusterPolicy(in *ClusterPolicy, out *v1.ClusterPolicy, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v2_Spec_To_v1_Spec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	out.Status = in.Status
	return nil
}

// Convert_v2_ClusterPolicy_To_v1_ClusterPolicy is an autogenerated conversion function.
func Convert_v2_ClusterPolicy_To_v1_ClusterPolicy(in *ClusterPolicy, out *v1.ClusterPolicy, s conversion.Scope) error {
	return autoConvert_v2_ClusterPolicy_To_v1_ClusterPolicy(in, out, s)
}

func autoConvert_v1_ClusterPolicy_To_v2_ClusterPolicy(in *v1.ClusterPolicy, out *ClusterPolicy, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1_Spec_To_v2_Spec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	out.Status = in.Status
	return nil
}

// Convert_v1_ClusterPolicy_To_v2_ClusterPolicy is an autogenerated conversion function.
func Convert_v1_ClusterPolicy_To_v2_ClusterPolicy(in *v1.ClusterPolicy, out *ClusterPolicy, s conversion.Scope) error {
	return autoConvert_v1_ClusterPolicy_To_v2_ClusterPolicy(in, out, s)
}

func autoConvert_v2_ClusterPolicyList_To_v1_ClusterPolicyList(in *ClusterPolicyList, out *v1.ClusterPolicyList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]v1.ClusterPolicy, len(*in))
		for i := range *in {
			if err := Convert_v2_ClusterPolicy_To_v1_ClusterPolicy(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v2_ClusterPolicyList_To_v1_ClusterPolicyList is an autogenerated conversion function.
func Convert_v2_ClusterPolicyList_To_v1_ClusterPolicyList(in *ClusterPolicyList, out *v1.ClusterPolicyList, s conversion.Scope) error {
	return autoConvert_v2_ClusterPolicyList_To_v1_ClusterPolicyList(in, out, s)
}

func autoConvert_v1_ClusterPolicyList_To_v2_ClusterPolicyList(in *v1.ClusterPolicyList, out *ClusterPolicyList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ClusterPolicy, len(*in))
		for i := range *in {
			if err := Convert_v1_ClusterPolicy_To_v2_ClusterPolicy(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1_ClusterPolicyList_To_v2_ClusterPolicyList is an autogenerated conversion function.
func Convert_v1_ClusterPolicyList_To_v2_ClusterPolicyList(in *v1.ClusterPolicyList, out *ClusterPolicyList, s conversion.Scope) error {
	return autoConvert_v1_ClusterPolicyList_To_v2_ClusterPolicyList(in, out, s)
}

func autoConvert_v2_Condition_To_v1_Condition(in *Condition, out *v1.Condition, s conversion.Scope) error {
	out.RawKey = (*apiextensionsv1.JSON)(unsafe.Pointer(in.RawKey))
	out.Operator = v1.ConditionOperator(in.Operator)
	out.RawValue = (*apiextensionsv1.JSON)(unsafe.Pointer(in.RawValue))
	out.Message = in.Message
	return nil
}

// Convert_v2_Condition_To_v1_Condition is an autogenerated conversion function.
func Convert_v2_Condition_To_v1_Condition(in *Condition, out *v1.Condition, s conversion.Scope) error {
	return autoConvert_v2_Condition_To_v1_Condition(in, out, s)
}

func autoConvert_v1_Condition_To_v2_Condition(in *v1.Condition, out *Condition, s conversion.Scope) error {
	out.RawKey = (*apiextensionsv1.JSON)(unsafe.Pointer(in.RawKey))
	out.Operator = ConditionOperator(in.Operator)
	out.RawValue = (*apiextensionsv1.JSON)(unsafe.Pointer(in.RawValue))
	out.Message = in.Message
	return nil
}

// Convert_v1_Condition_To_v2_Condition is an autogenerated conversion function.
func Convert_v1_Condition_To_v2_Condition(in *v1.Condition, out *Condition, s conversion.Scope) error {
	return autoConvert_v1_Condition_To_v2_Condition(in, out, s)
}

func autoConvert_v2_Generation_To_v1_Generation(in *Generation, out *v1.Generation, s conversion.Scope) error {
	out.ResourceSpec = in.ResourceSpec
	// WARNING: in.GenerateExisting requires manual conversion: does not exist in peer-type
	out.Synchronize = in.Synchronize
	out.OrphanDownstreamOnPolicyDelete = in.OrphanDownstreamOnPolicyDelete
	out.RawData = (*apiextensionsv1.JSON)(unsafe.Pointer(in.RawData))
	out.Clone = in.Clone
	out.CloneList = in.CloneList
	return nil
}

func autoConvert_v1_Generation_To_v2_Generation(in *v1.Generation, out *Generation, s conversion.Scope) error {
	out.ResourceSpec = in.ResourceSpec
	out.Synchronize = in.Synchronize
	out.OrphanDownstreamOnPolicyDelete = in.OrphanDownstreamOnPolicyDelete
	out.RawData = (*apiextensionsv1.JSON)(unsafe.Pointer(in.RawData))
	out.Clone = in.Clone
	out.CloneList = in.CloneList
	return nil
}

// Convert_v1_Generation_To_v2_Generation is an autogenerated conversion function.
func Convert_v1_Generation_To_v2_Generation(in *v1.Generation, out *Generation, s conversion.Scope) error {
	return autoConvert_v1_Generation_To_v2_Generation(in, out, s)
}

func autoConvert_v2_ImageVerification_To_v1_ImageVerification(in *ImageVerification, out *v1.ImageVerification, s conversion.Scope) error {
	out.Type = v1.ImageVerificationType(in.Type)
	out.ImageReferences = *(*[]string)(unsafe.Pointer(&in.ImageReferences))
	out.SkipImageReferences = *(*[]string)(unsafe.Pointer(&in.SkipImageReferences))
	out.Attestors = *(*[]v1.AttestorSet)(unsafe.Pointer(&in.Attestors))
	if in.Attestations != nil {
		in, out := &in.Attestations, &out.Attestations
		*out = make([]v1.Attestation, len(*in))
		for i := range *in {
			if err := Convert_v2_Attestation_To_v1_Attestation(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Attestations = nil
	}
	out.Repository = in.Repository
	out.MutateDigest = in.MutateDigest
	out.VerifyDigest = in.VerifyDigest
	out.Required = in.Required
	out.ImageRegistryCredentials = (*v1.ImageRegistryCredentials)(unsafe.Pointer(in.ImageRegistryCredentials))
	out.UseCache = in.UseCache
	return nil
}

// Convert_v2_ImageVerification_To_v1_ImageVerification is an autogenerated conversion function.
func Convert_v2_ImageVerification_To_v1_ImageVerification(in *ImageVerification, out *v1.ImageVerification, s conversion.Scope) error {
	return autoConvert_v2_ImageVerification_To_v1_ImageVerification(in, out, s)
}

func autoConvert_v1_ImageVerification_To_v2_ImageVerification(in *v1.ImageVerification, out *ImageVerification, s conversion.Scope) error {
	out.Type = v1.ImageVerificationType(in.Type)
	// WARNING: in.Image requires manual conversion: does not exist in peer-type
	out.ImageReferences = *(*[]string)(unsafe.Pointer(&in.ImageReferences))
	out.SkipImageReferences = *(*[]string)(unsafe.Pointer(&in.SkipImageReferences))
	// WARNING: in.Key requires manual conversion: does not exist in peer-type
	// WARNING: in.Roots requires manual conversion: does not exist in peer-type
	// WARNING: in.Subject requires manual conversion: does not exist in peer-type
	// WARNING: in.Issuer requires manual conversion: does not exist in peer-type
	// WARNING: in.AdditionalExtensions requires manual conversion: does not exist in peer-type
	out.Attestors = *(*[]v1.AttestorSet)(unsafe.Pointer(&in.Attestors))
	if in.Attestations != nil {
		in, out := &in.Attestations, &out.Attestations
		*out = make([]Attestation, len(*in))
		for i := range *in {
			if err := Convert_v1_Attestation_To_v2_Attestation(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Attestations = nil
	}
	// WARNING: in.Annotations requires manual conversion: does not exist in peer-type
	out.Repository = in.Repository
	out.MutateDigest = in.MutateDigest
	out.VerifyDigest = in.VerifyDigest
	out.Required = in.Required
	out.ImageRegistryCredentials = (*v1.ImageRegistryCredentials)(unsafe.Pointer(in.ImageRegistryCredentials))
	out.UseCache = in.UseCache
	return nil
}

func autoConvert_v2_MatchResources_To_v1_MatchResources(in *MatchResources, out *v1.MatchResources, s conversion.Scope) error {
	if in.Any != nil {
		in, out := &in.Any, &out.Any
		*out = make(v1.ResourceFilters, len(*in))
		for i := range *in {
			if err := Convert_v2_ResourceFilter_To_v1_ResourceFilter(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Any = nil
	}
	if in.All != nil {
		in, out := &in.All, &out.All
		*out = make(v1.ResourceFilters, len(*in))
		for i := range *in {
			if err := Convert_v2_ResourceFilter_To_v1_ResourceFilter(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.All = nil
	}
	return nil
}

// Convert_v2_MatchResources_To_v1_MatchResources is an autogenerated conversion function.
func Convert_v2_MatchResources_To_v1_MatchResources(in *MatchResources, out *v1.MatchResources, s conversion.Scope) error {
	return autoConvert_v2_MatchResources_To_v1_MatchResources(in, out, s)
}

func autoConvert_v1_MatchResources_To_v2_MatchResources(in *v1.MatchResources, out *MatchResources, s conversion.Scope) error {
	if in.Any != nil {
		in, out := &in.Any, &out.Any
		*out = make(ResourceFilters, len(*in))
		for i := range *in {
			if err := Convert_v1_ResourceFilter_To_v2_ResourceFilter(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Any = nil
	}
	if in.All != nil {
		in, out := &in.All, &out.All
		*out = make(ResourceFilters, len(*in))
		for i := range *in {
			if err := Convert_v1_ResourceFilter_To_v2_ResourceFilter(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.All = nil
	}
	// WARNING: in.UserInfo requires manual conversion: does not exist in peer-type
	// WARNING: in.ResourceDescription requires manual conversion: does not exist in peer-type
	return nil
}

func autoConvert_v2_Mutation_To_v1_Mutation(in *Mutation, out *v1.Mutation, s conversion.Scope) error {
	// WARNING: in.MutateExistingOnPolicyUpdate requires manual conversion: does not exist in peer-type
	if in.Targets != nil {
		in, out := &in.Targets, &out.Targets
		*out = make([]v1.TargetResourceSpec, len(*in))
		for i := range *in {
			if err := Convert_v2_TargetResourceSpec_To_v1_TargetResourceSpec(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Targets = nil
	}
	out.RawPatchStrategicMerge = (*apiextensionsv1.JSON)(unsafe.Pointer(in.RawPatchStrategicMerge))
	out.PatchesJSON6902 = in.PatchesJSON6902
	out.ForEachMutation = *(*[]v1.ForEachMutation)(unsafe.Pointer(&in.ForEachMutation))
	return nil
}

func autoConvert_v1_Mutation_To_v2_Mutation(in *v1.Mutation, out *Mutation, s conversion.Scope) error {
	if in.Targets != nil {
		in, out := &in.Targets, &out.Targets
		*out = make([]TargetResourceSpec, len(*in))
		for i := range *in {
			if err := Convert_v1_TargetResourceSpec_To_v2_TargetResourceSpec(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Targets = nil
	}
	out.RawPatchStrategicMerge = (*apiextensionsv1.JSON)(unsafe.Pointer(in.RawPatchStrategicMerge))
	out.PatchesJSON6902 = in.PatchesJSON6902
	out.ForEachMutation = *(*[]v1.ForEachMutation)(unsafe.Pointer(&in.ForEachMutation))
	return nil
}

// Convert_v1_Mutation_To_v2_Mutation is an autogenerated conversion function.
func Convert_v1_Mutation_To_v2_Mutation(in *v1.Mutation, out *Mutation, s conversion.Scope) error {
	return autoConvert_v1_Mutation_To_v2_Mutation(in, out, s)
}

func autoConvert_v2_Policy_To_v1_Policy(in *Policy, out *v1.Policy, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v2_Spec_To_v1_Spec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	out.Status = in.Status
	return nil
}

// Convert_v2_Policy_To_v1_Policy is an autogenerated conversion function.
func Convert_v2_Policy_To_v1_Policy(in *Policy, out *v1.Policy, s conversion.Scope) error {
	return autoConvert_v2_Policy_To_v1_Policy(in, out, s)
}

func autoConvert_v1_Policy_To_v2_Policy(in *v1.Policy, out *Policy, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1_Spec_To_v2_Spec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	out.Status = in.Status
	return nil
}

// Convert_v1_Policy_To_v2_Policy is an autogenerated conversion function.
func Convert_v1_Policy_To_v2_Policy(in *v1.Policy, out *Policy, s conversion.Scope) error {
	return autoConvert_v1_Policy_To_v2_Policy(in, out, s)
}

func autoConvert_v2_PolicyList_To_v1_PolicyList(in *PolicyList, out *v1.PolicyList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]v1.Policy, len(*in))
		for i := range *in {
			if err := Convert_v2_Policy_To_v1_Policy(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v2_PolicyList_To_v1_PolicyList is an autogenerated conversion function.
func Convert_v2_PolicyList_To_v1_PolicyList(in *PolicyList, out *v1.PolicyList, s conversion.Scope) error {
	return autoConvert_v2_PolicyList_To_v1_PolicyList(in, out, s)
}

func autoConvert_v1_PolicyList_To_v2_PolicyList(in *v1.PolicyList, out *PolicyList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Policy, len(*in))
		for i := range *in {
			if err := Convert_v1_Policy_To_v2_Policy(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1_PolicyList_To_v2_PolicyList is an autogenerated conversion function.
func Convert_v1_PolicyList_To_v2_PolicyList(in *v1.PolicyList, out *PolicyList, s conversion.Scope) error {
	return autoConvert_v1_PolicyList_To_v2_PolicyList(in, out, s)
}

func autoConvert_v2_ResourceDescription_To_v1_ResourceDescription(in *ResourceDescription, out *v1.ResourceDescription, s conversion.Scope) error {
	out.Kinds = *(*[]string)(unsafe.Pointer(&in.Kinds))
	out.Names = *(*[]string)(unsafe.Pointer(&in.Names))
	out.Namespaces = *(*[]string)(unsafe.Pointer(&in.Namespaces))
	out.Annotations = *(*map[string]string)(unsafe.Pointer(&in.Annotations))
	out.Selector = (*metav1.LabelSelector)(unsafe.Pointer(in.Selector))
	out.NamespaceSelector = (*metav1.LabelSelector)(unsafe.Pointer(in.NamespaceSelector))
	out.Operations = *(*[]v1.AdmissionOperation)(unsafe.Pointer(&in.Operations))
	return nil
}

// Convert_v2_ResourceDescription_To_v1_ResourceDescription is an autogenerated conversion function.
func Convert_v2_ResourceDescription_To_v1_ResourceDescription(in *ResourceDescription, out *v1.ResourceDescription, s conversion.Scope) error {
	return autoConvert_v2_ResourceDescription_To_v1_ResourceDescription(in, out, s)
}

func autoConvert_v1_ResourceDescription_To_v2_ResourceDescription(in *v1.ResourceDescription, out *ResourceDescription, s conversion.Scope) error {
	out.Kinds = *(*[]string)(unsafe.Pointer(&in.Kinds))
	// WARNING: in.Name requires manual conversion: does not exist in peer-type
	out.Names = *(*[]string)(unsafe.Pointer(&in.Names))
	out.Namespaces = *(*[]string)(unsafe.Pointer(&in.Namespaces))
	out.Annotations = *(*map[string]string)(unsafe.Pointer(&in.Annotations))
	out.Selector = (*metav1.LabelSelector)(unsafe.Pointer(in.Selector))
	out.NamespaceSelector = (*metav1.LabelSelector)(unsafe.Pointer(in.NamespaceSelector))
	out.Operations = *(*[]v1.AdmissionOperation)(unsafe.Pointer(&in.Operations))
	return nil
}

func autoConvert_v2_ResourceFilter_To_v1_ResourceFilter(in *ResourceFilter, out *v1.ResourceFilter, s conversion.Scope) error {
	out.UserInfo = in.UserInfo
	if err := Convert_v2_ResourceDescription_To_v1_ResourceDescription(&in.ResourceDescription, &out.ResourceDescription, s); err != nil {
		return err
	}
	return nil
}

// Convert_v2_ResourceFilter_To_v1_ResourceFilter is an autogenerated conversion function.
func Convert_v2_ResourceFilter_To_v1_ResourceFilter(in *ResourceFilter, out *v1.ResourceFilter, s conversion.Scope) error {
	return autoConvert_v2_ResourceFilter_To_v1_ResourceFilter(in, out, s)
}

func autoConvert_v1_ResourceFilter_To_v2_ResourceFilter(in *v1.ResourceFilter, out *ResourceFilter, s conversion.Scope) error {
	out.UserInfo = in.UserInfo
	if err := Convert_v1_ResourceDescription_To_v2_ResourceDescription(&in.ResourceDescription, &out.ResourceDescription, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1_ResourceFilter_To_v2_ResourceFilter is an autogenerated conversion function.
func Convert_v1_ResourceFilter_To_v2_ResourceFilter(in *v1.ResourceFilter, out *ResourceFilter, s conversion.Scope) error {
	return autoConvert_v1_ResourceFilter_To_v2_ResourceFilter(in, out, s)
}

func autoConvert_v2_Spec_To_v1_Spec(in *Spec, out *v1.Spec, s conversion.Scope) error {
	if in.Rules != nil {
		in, out := &in.Rules, &out.Rules
		*out = make([]v1.Rule, len(*in))
		for i := range *in {
			if err := Convert_v2_Rule_To_v1_Rule(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Rules = nil
	}
	out.ApplyRules = (*v1.ApplyRulesType)(unsafe.Pointer(in.ApplyRules))
	out.FailurePolicy = (*v1.FailurePolicyType)(unsafe.Pointer(in.FailurePolicy))
	out.Admission = (*bool)(unsafe.Pointer(in.Admission))
	out.Background = (*bool)(unsafe.Pointer(in.Background))
	out.WebhookTimeoutSeconds = (*int32)(unsafe.Pointer(in.WebhookTimeoutSeconds))
	out.UseServerSideApply = in.UseServerSideApply
	out.WebhookConfiguration = (*v1.WebhookConfiguration)(unsafe.Pointer(in.WebhookConfiguration))
	return nil
}

func autoConvert_v1_Spec_To_v2_Spec(in *v1.Spec, out *Spec, s conversion.Scope) error {
	if in.Rules != nil {
		in, out := &in.Rules, &out.Rules
		*out = make([]Rule, len(*in))
		for i := range *in {
			if err := Convert_v1_Rule_To_v2_Rule(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Rules = nil
	}
	out.ApplyRules = (*v1.ApplyRulesType)(unsafe.Pointer(in.ApplyRules))
	out.FailurePolicy = (*v1.FailurePolicyType)(unsafe.Pointer(in.FailurePolicy))
	// WARNING: in.ValidationFailureAction requires manual conversion: does not exist in peer-type
	// WARNING: in.ValidationFailureActionOverrides requires manual conversion: does not exist in peer-type
	out.Admission = (*bool)(unsafe.Pointer(in.Admission))
	out.Background = (*bool)(unsafe.Pointer(in.Background))
	// WARNING: in.SchemaValidation requires manual conversion: does not exist in peer-type
	out.WebhookTimeoutSeconds = (*int32)(unsafe.Pointer(in.WebhookTimeoutSeconds))
	// WARNING: in.MutateExistingOnPolicyUpdate requires manual conversion: does not exist in peer-type
	// WARNING: in.GenerateExistingOnPolicyUpdate requires manual conversion: does not exist in peer-type
	// WARNING: in.GenerateExisting requires manual conversion: does not exist in peer-type
	out.UseServerSideApply = in.UseServerSideApply
	out.WebhookConfiguration = (*WebhookConfiguration)(unsafe.Pointer(in.WebhookConfiguration))
	return nil
}

func autoConvert_v2_Validation_To_v1_Validation(in *Validation, out *v1.Validation, s conversion.Scope) error {
	// WARNING: in.ValidationFailureAction requires manual conversion: does not exist in peer-type
	// WARNING: in.ValidationFailureActionOverrides requires manual conversion: does not exist in peer-type
	out.Message = in.Message
	out.Manifests = (*v1.Manifests)(unsafe.Pointer(in.Manifests))
	out.ForEachValidation = *(*[]v1.ForEachValidation)(unsafe.Pointer(&in.ForEachValidation))
	out.RawPattern = (*apiextensionsv1.JSON)(unsafe.Pointer(in.RawPattern))
	out.RawAnyPattern = (*apiextensionsv1.JSON)(unsafe.Pointer(in.RawAnyPattern))
	if in.Deny != nil {
		in, out := &in.Deny, &out.Deny
		*out = new(v1.Deny)
		if err := Convert_v2_Deny_To_v1_Deny(*in, *out, s); err != nil {
			return err
		}
	} else {
		out.Deny = nil
	}
	out.PodSecurity = (*v1.PodSecurity)(unsafe.Pointer(in.PodSecurity))
	out.CEL = (*v1.CEL)(unsafe.Pointer(in.CEL))
	return nil
}

func autoConvert_v1_Validation_To_v2_Validation(in *v1.Validation, out *Validation, s conversion.Scope) error {
	out.Message = in.Message
	out.Manifests = (*v1.Manifests)(unsafe.Pointer(in.Manifests))
	out.ForEachValidation = *(*[]v1.ForEachValidation)(unsafe.Pointer(&in.ForEachValidation))
	out.RawPattern = (*apiextensionsv1.JSON)(unsafe.Pointer(in.RawPattern))
	out.RawAnyPattern = (*apiextensionsv1.JSON)(unsafe.Pointer(in.RawAnyPattern))
	if in.Deny != nil {
		in, out := &in.Deny, &out.Deny
		*out = new(Deny)
		if err := Convert_v1_Deny_To_v2_Deny(*in, *out, s); err != nil {
			return err
		}
	} else {
		out.Deny = nil
	}
	out.PodSecurity = (*v1.PodSecurity)(unsafe.Pointer(in.PodSecurity))
	out.CEL = (*v1.CEL)(unsafe.Pointer(in.CEL))
	return nil
}

// Convert_v1_Validation_To_v2_Validation is an autogenerated conversion function.
func Convert_v1_Validation_To_v2_Validation(in *v1.Validation, out *Validation, s conversion.Scope) error {
	return autoConvert_v1_Validation_To_v2_Validation(in, out, s)
}

func autoConvert_v2_WebhookConfiguration_To_v1_WebhookConfiguration(in *WebhookConfiguration, out *v1.WebhookConfiguration, s conversion.Scope) error {
	out.MatchConditions = *(*[]admissionregistrationv1.MatchCondition)(unsafe.Pointer(&in.MatchConditions))
	return nil
}

// Convert_v2_WebhookConfiguration_To_v1_WebhookConfiguration is an autogenerated conversion function.
func Convert_v2_WebhookConfiguration_To_v1_WebhookConfiguration(in *WebhookConfiguration, out *v1.WebhookConfiguration, s conversion.Scope) error {
	return autoConvert_v2_WebhookConfiguration_To_v1_WebhookConfiguration(in, out, s)
}

func autoConvert_v1_WebhookConfiguration_To_v2_WebhookConfiguration(in *v1.WebhookConfiguration, out *WebhookConfiguration, s conversion.Scope) error {
	out.MatchConditions = *(*[]admissionregistrationv1.MatchCondition)(unsafe.Pointer(&in.MatchConditions))
	return nil
}

// Convert_v1_WebhookConfiguration_To_v2_WebhookConfiguration is an autogenerated conversion function.
func Convert_v1_WebhookConfiguration_To_v2_WebhookConfiguration(in *v1.WebhookConfiguration, out *WebhookConfiguration, s conversion.Scope) error {
	return autoConvert_v1_WebhookConfiguration_To_v2_WebhookConfiguration(in, out, s)
}
